# Autogenerated wrapper script for azurite_jll for any
export azurite

using NodeJS_16_jll
JLLWrappers.@generate_wrapper_header("azurite")
JLLWrappers.@declare_file_product(azurite)
function __init__()
    JLLWrappers.@generate_init_header(NodeJS_16_jll)
    JLLWrappers.@init_file_product(
        azurite,
        "node_modules/azurite/dist/src/azurite.js",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
